### ISSUE TITLE
I didn't see anything except a black image

### ISSUE THREAD

**Issue by StevenHuang4321** [fashiontec/bodyapps-viz#11]
I used Chrome and IE to open the index.html, but what i can find is only a black image.
Is there anything wrong with my operation.

**Comment by prasht63** [comment]
Hi Steven
You will be needing a webserver(WAMP , XAMPP or just Apache Tomcat would do) to run the Body Visualiser . As for the black screen can you see the developer console to see if there is any broken link.Sometimes there's a problem with case sensitivity. For a live working demo I would suggest you to see http://prasht63.github.io/bodyapps-viz/
